name: CI/CD for Movie Ticket Frontend with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run lint
        run: pnpm lint

      - name: Build project
        run: pnpm build
        # Vue sẽ tạo dist/, React sẽ tạo build/

  cd:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install rsync and SSH client
        run: |
          sudo apt-get update
          sudo apt-get install -y rsync openssh-client

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GCP_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.GCP_VM_IP }} >> ~/.ssh/known_hosts

      - name: Ensure destination folder exists on VM
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.GCP_SSH_USER }}@${{ secrets.GCP_VM_IP }} "
            mkdir -p /tmp/movie-ticket-web
          "

      - name: Deploy to Compute Engine
        run: |
          # Ensure rsync exists on VM
          ssh -i ~/.ssh/id_rsa ${{ secrets.GCP_SSH_USER }}@${{ secrets.GCP_VM_IP }} "which rsync || (sudo apt-get update && sudo apt-get install -y rsync)"

          # Copy toàn bộ project (trừ node_modules/.env)
          rsync -avz --delete --exclude '.env' --exclude 'node_modules' -e "ssh -i ~/.ssh/id_rsa" . ${{ secrets.GCP_SSH_USER }}@${{ secrets.GCP_VM_IP }}:/tmp/movie-ticket-web

          # Deploy trong VM
          ssh -i ~/.ssh/id_rsa ${{ secrets.GCP_SSH_USER }}@${{ secrets.GCP_VM_IP }} << 'EOF'
            if ! command -v docker compose &> /dev/null; then
              sudo apt-get update
              sudo apt-get install -y docker-compose-plugin
            fi

            cd /tmp/movie-ticket-web

            # Copy .env có sẵn từ /resource vào thư mục project
            cp /resource-internal/.env .env

            docker compose up -d --build

            # Cleanup temp files
            rm -rf /tmp/movie-ticket-web
          EOF
